### ISSUE TITLE
Feature Request: Battery low notification

### ISSUE THREAD

**Issue by vertigo220** [ViGEm/DsHidMini#128]
Not sure if this is where you want feature requests, but it doesn't look like there's a spot on the forum for them, either.

I actually didn't realize until I read another issue just now, searching for an open one regarding this, that the LEDs on the controller indicate the charge level, so that's good to know, but maybe that info should be mentioned in the battery status tooltip or something. But what I'd really like is a notification that pops up when the battery reaches a user-defined level, and even better one for discharging and charging, e.g. when discharged down to 20% so I know to plug it in and when charged to 90% so I know I can unplug it. And an additional option could be to simply play a sound, with the option to repeat it periodically, so those that wouldn't want a visible pop-up getting in the way of their game, or in case the pop-up wouldn't show over the game, could still be alerted, and with the repeat they would hear it if they missed it the first time. So, for example, it could do a double-beep every 5 minutes.

Another possible addition here, though not as important, would be battery level tracking, so it could be viewed on a graph to give an idea of how long it's lasting, and this would also allow it to be set to warn when there's x minutes left instead of y%.

**Comment by nefarius** [comment]
It is literally mentioned directly in the project README **and multiple times** on the project documentation site that the LEDs are used as charge indicator. It even flashes when it enters low/dying state.

Displaying notifications or playing sounds (no, I did that in SCP and got enough PTSD from that for 10 life times) isn't a task for a driver, it requires a user-land tool that constantly runs in the background and requires significant thought and dedication.

I consider this out of scope since the potential values does in no way warrant the required energy to get this off the ground.

In regards to feature requests; I think it is clearly outlined how to do, the Discussions tab for example would've been a stellar candidate, or the Discord server.
