### ISSUE TITLE
On `DS4Windows` Mode, the `pairing attempt` check will always be marked as failed

### ISSUE THREAD

**Issue by Kanuan** [ViGEm/DsHidMini#86]
On the new, yet unreleased DS4Windows mode, the last pairing attempt will always result in a fail, at least according to DSHMC.
Don't know if the pairing is actually failing or if DSHMC is just failing to properly check its status

![image](https://user-images.githubusercontent.com/24910442/117760870-c6cb0180-b1fc-11eb-975a-bab3a1d84305.png)

**Comment by nefarius** [comment]
That was probably me during the last major refactoring run, I remember touching that function. I'll look through the differences and see what I can do. Thanks!

**Comment by nefarius** [comment]
Oh, or is it really mode-dependant?

**Comment by nefarius** [comment]
Can you check the property what the exact error code is in your case?

![image](https://user-images.githubusercontent.com/286631/117861021-3be81680-b291-11eb-9e83-234ddce8b3e7.png)

Because I got it now as well while plugging it in (in new XInput mode):

![image](https://user-images.githubusercontent.com/286631/117861078-502c1380-b291-11eb-9552-9d7888b35446.png)

**Comment by Kanuan** [comment]
> Can you check the property what the exact error code is in your case?

It's the exact same as yours

**Comment by nefarius** [comment]
> > Can you check the property what the exact error code is in your case?
> 
> It's the exact same as yours

Then I am quite certain this is the case. I added the check in the refactoring, to avoid re-pairing to the same radio which avoids sending an unnecessary packet.
